.circleci/config.yml
package.json

Update how we use the orb

---

.circleci/config.yml
commitlint.config.js
package.json
yarn.lock

Adds commit linting
Uses the latest npm-release-management-orb
@W-7978545@
@W-7919544@

feat: add commit linting and use latest orb

---

.circleci/config.yml
messages/get.json
messages/list.json
messages/set.json
messages/unset.json
package.json
src/commands/config/get.ts
src/commands/config/list.ts
src/commands/config/set.ts
src/commands/config/unset.ts
src/config.ts
yarn.lock

Updates descriptions and adds examples
NA

fix: update command messages

---

.circleci/config.yml

Updates config.yml to include PR validation
@W-7978550@

Use orb to validate PRs

---

.eslintrc.js
.gitignore
.mocharc.json
.nycrc
.prettierrc
.prettierrc.json
LICENSE.txt
package.json
src/commands/config/get.ts
src/commands/config/list.ts
src/commands/config/set.ts
src/commands/config/unset.ts
src/config.ts
test/.eslintrc.js
test/commands/config/get.test.ts
test/commands/config/list.test.ts
test/commands/config/set.test.ts
test/commands/config/unset.test.ts
test/mocha.opts
test/tsconfig.json
tsconfig.json
tslint.json
yarn.lock

Moves project to eslint
@W-8100106@
Closes https://github.com/salesforcecli/plugin-config/pull/13

chore: tslint -> eslint

---

messages/list.json
messages/set.json

Updates help output
@W-8246223@

chore: update help output

---

package.json
test/commands/config/set.test.ts
yarn.lock

Bumps @salesforce/command and fixes mocking by mocking the specific method used to load config for error cases

fix: bump @salesforce/command and fix config mocking

---

.circleci/config.yml
yarn.lock

fix: bumped npm release to v4 @W-8437381@

---

package.json

chore: bump package.json [skip-ci]

---

.circleci/config.yml

merges PRs while we sleep
@W-9477765@

chore: automerge

---

.mocharc.json
bin/dev
bin/dev.cmd
bin/run
command-snapshot.json
messages/set.json
package.json
schemas/config-get.json
schemas/config-list.json
schemas/config-set.json
schemas/config-unset.json
src/commands/config/get.ts
src/commands/config/list.ts
src/commands/config/set.ts
src/commands/config/unset.ts
src/config.ts
src/hooks/init/load_config_meta.ts
test/commands/config/get.nut.ts
test/commands/config/get.test.ts
test/commands/config/list.nut.ts
test/commands/config/list.test.ts
test/commands/config/set.nut.ts
test/commands/config/set.test.ts
test/commands/config/unset.nut.ts
test/commands/config/unset.test.ts
test/hooks/load_config_meta.test.ts
test/interoperability.nut.ts
yarn.lock

Migrates config commands to oclif/core
@W-9641000@

refactor: migrate to oclif/core

---

package.json

update "config" topic description in package.json
@W-9622455@

update "config" topic description in package.json

---

package.json
src/config.ts
test/commands/config/get.nut.ts
test/commands/config/set.nut.ts
test/commands/config/unset.nut.ts
yarn.lock

Replaces `undefined` values with empty strings when displaying table
@W-9672293@
@W-9709972@

fix: dont show undefined in table

---

package.json
src/commands/config/get.ts
src/commands/config/set.ts
src/commands/config/unset.ts
test/commands/config/get.nut.ts
test/commands/config/get.test.ts
test/commands/config/list.nut.ts
test/commands/config/list.test.ts
test/commands/config/set.nut.ts
test/commands/config/set.test.ts
test/commands/config/unset.nut.ts
test/commands/config/unset.test.ts
test/interoperability.nut.ts
yarn.lock

Uses for `@salesforce/core@3.4.0` for latest config interoperability changes
@W-9735962@

feat: use @salesforce/core@3.4.0

---

package.json

update "config" topic description to say "commands to...", in line with other topics
@W-9697231@

fix: update topic description

---

package.json
test/interoperability.nut.ts
yarn.lock

- bumps core to 3.4.2
- adds more interoperability tests
@W-9735962@

fix: bump core and add more tests

---

messages/get.md
messages/set.md

Small updates to help for "sf config get" and "sf config set"
@W-9771396@

small updates to help

---

package.json
yarn.lock

fix: bump oclif/core and @salesforce/core

---

package.json
test/commands/config/set.nut.ts
yarn.lock

fixes a NUT where the error message varies depending on node version (not OS)
NUT-change only, no QA required.
related to @W-9346211@ and https://github.com/salesforcecli/plugin-config/pull/169

test: url may or may not be included in error

---

package.json
src/commands/config/get.ts
src/commands/config/list.ts
src/commands/config/set.ts
src/commands/config/unset.ts
src/config.ts
test/commands/config/get.nut.ts
test/commands/config/get.test.ts
test/commands/config/list.nut.ts
test/commands/config/list.test.ts
test/commands/config/set.nut.ts
test/commands/config/set.test.ts
test/commands/config/unset.nut.ts
test/commands/config/unset.test.ts
test/interoperability.nut.ts
yarn.lock

Use `SfCommand`
[skip-validate-pr]

feat: use SfCommand

---

package.json
src/commands/config/get.ts
src/commands/config/set.ts
src/commands/config/unset.ts
src/config.ts
src/hooks/init/load_config_meta.ts
yarn.lock

Add additional help section to commands that have something more today ;) 
@W-9791511

fix: add help section commands

---

.mocharc.json
package.json
src/commands/config/get.ts
src/commands/config/set.ts
src/commands/config/unset.ts
src/config.ts
src/hooks/init/load_config_meta.ts
yarn.lock

Increases test timeout to 10 seconds
@W-9791511@

fix: increase test timeout to 10 seconds

---

CHANGELOG.md
package.json
test/commands/config/set.nut.ts
yarn.lock

Merges `main` into `v2`
[skip-validate-pr]

Merge `main` into `v2`

---

package.json
src/commands/config/get.ts
src/commands/config/set.ts
src/commands/config/unset.ts
src/config.ts
yarn.lock

fix: replace command with sf-plugins-core

---

messages/get.md
messages/set.md
messages/unset.md
src/config.ts
test/commands/config/get.nut.ts
test/commands/config/unset.nut.ts

Minor edits to some error messages.
@W-9676027@

fix: error message edits

---

package.json
yarn.lock

bump oclif/core and plugins-core to v1

fix: bump oclif/core and plugins-core to v1 [skip-validate-pr]

---

package.json
test/commands/config/set.nut.ts
yarn.lock

Bump `sfdx-core` to 2.28.3 and make NUTs ignore error messages.
@W-0@

fix: bump sfdx-core and fix NUT

---

.nycrc
package.json
yarn.lock

Fix deps conflict caused by dev-script in this PR: https://github.com/salesforcecli/plugin-config/pull/252
@W-8776236@

chore: fix dev-config conflict

---

package.json
test/interoperability.nut.ts
yarn.lock

removes the `fs` import from `sfdx-core`
@W-10771372@

test: remove fs from core

---

package.json
yarn.lock

Adds caret to `@salesforce/core` so that all plugins using CoreV3 will have the same version.
Also preparation for rotating file logs in v3.
[@W-10745422@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-10745422)

Add caret to @salesforce/core

---

.circleci/config.yml

Adds AWS context to the v2 branch so that we can deploy
[@W-10745422@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-10745422)

Add AWS CircleCI context

---

messages/get.json
messages/set.json
messages/unset.json

Adds prompt to examples so that they're correctly tagged with <codeblock> in the generated CLI Ref.
@W-11159165@

Add prompt to example

---

package.json
test/commands/config/get.nut.ts
test/commands/config/list.nut.ts
test/commands/config/set.nut.ts
test/commands/config/unset.nut.ts
yarn.lock

Use latest cli-plugins-testkit
@W-11823417@

chore: update to latest testkit

---

.github/workflows/failureNotifications.yml
.github/workflows/test.yml
README.md
bin/dev
bin/dev.cmd
command-snapshot.json
package.json
src/commands/config/unset.ts
yarn.lock

[@W-11976301@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-11976301)

Add SWC and sync files

---

LICENSE.txt
package.json
src/config.ts
test/commands/config/get.test.ts
yarn.lock

Uses sf-plugins-core v2 and oclif/core v2
@W-10791948@

feat: use latest oclif/core
